import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1754274244618 implements MigrationInterface {
    name = 'InitialMigration1754274244618'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_0cb93c5877d37e954e2aa59e52c"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_d422dabc78ff74a8dab6583da02"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_13380e7efec83468d73fc37938e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cb93c5877d37e954e2aa59e52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d422dabc78ff74a8dab6583da0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13380e7efec83468d73fc37938"`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME COLUMN "rolesId" TO "rolesRoleuuid"`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME CONSTRAINT "PK_cd27695a2971731e9fc91b380b3" TO "PK_eb213c3c5ab595f0d0b3b759daf"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "PK_920331560282b8bd21bb02290df"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "UQ_48ce552495d14eae9b187bb6716"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "PK_c1433d71a4838793a49dcad46ab"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "PK_7931614007a93423204b4b73240"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "PK_d422dabc78ff74a8dab6583da02" PRIMARY KEY ("permissionsId")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "rolesId"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "PK_d422dabc78ff74a8dab6583da02"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "permissionsId"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "permissionuuid" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "PK_83188322b7fef38680a2783120b" PRIMARY KEY ("permissionuuid")`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "permissionname" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "UQ_7e4f8955cf9f64918c743f10e0e" UNIQUE ("permissionname")`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "permissiondesc" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "permissioncode" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "UQ_7fee0e03939569cc9568b0f129e" UNIQUE ("permissioncode")`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "createdAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "roleuuid" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "PK_e6fccd3737d29284a4b871aced0" PRIMARY KEY ("roleuuid")`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "rolename" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_2db66a4809c8d953c3cd1975c55" UNIQUE ("rolename")`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "roledesc" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "rolecode" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_6499681055776dfd16a6d6113b1" UNIQUE ("rolecode")`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "createdAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "useremail" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "usercountrycode" character varying(3)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "userphone" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "usergender" character varying(2)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "userprofession" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "useraddress" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "dateOfBirth" date`);
        await queryRunner.query(`ALTER TABLE "users" ADD "city" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "state" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "country" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isActive" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "rolesRoleuuid" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "PK_c2fc5dc730b1d066bd5e49be4ba" PRIMARY KEY ("rolesRoleuuid")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "permissionsPermissionuuid" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "PK_c2fc5dc730b1d066bd5e49be4ba"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "PK_e6b70f947eb6319fd68d1f747d2" PRIMARY KEY ("rolesRoleuuid", "permissionsPermissionuuid")`);
        await queryRunner.query(`CREATE INDEX "IDX_c2fc5dc730b1d066bd5e49be4b" ON "role_permissions" ("rolesRoleuuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_ead3f9cac75269077249800856" ON "role_permissions" ("permissionsPermissionuuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_cafb0b8f7f6f2361bdfb0f225d" ON "user_roles" ("rolesRoleuuid") `);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_c2fc5dc730b1d066bd5e49be4ba" FOREIGN KEY ("rolesRoleuuid") REFERENCES "roles"("roleuuid") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_ead3f9cac752690772498008564" FOREIGN KEY ("permissionsPermissionuuid") REFERENCES "permissions"("permissionuuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_cafb0b8f7f6f2361bdfb0f225df" FOREIGN KEY ("rolesRoleuuid") REFERENCES "roles"("roleuuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_cafb0b8f7f6f2361bdfb0f225df"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_ead3f9cac752690772498008564"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_c2fc5dc730b1d066bd5e49be4ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cafb0b8f7f6f2361bdfb0f225d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ead3f9cac75269077249800856"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2fc5dc730b1d066bd5e49be4b"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "PK_e6b70f947eb6319fd68d1f747d2"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "PK_c2fc5dc730b1d066bd5e49be4ba" PRIMARY KEY ("rolesRoleuuid")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "permissionsPermissionuuid"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "PK_c2fc5dc730b1d066bd5e49be4ba"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "rolesRoleuuid"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "dateOfBirth"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "useraddress"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "userprofession"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "usergender"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "userphone"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "usercountrycode"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "useremail"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_6499681055776dfd16a6d6113b1"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "rolecode"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "roledesc"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_2db66a4809c8d953c3cd1975c55"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "rolename"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "PK_e6fccd3737d29284a4b871aced0"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "roleuuid"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "UQ_7fee0e03939569cc9568b0f129e"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "permissioncode"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "permissiondesc"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "UQ_7e4f8955cf9f64918c743f10e0e"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "permissionname"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "PK_83188322b7fef38680a2783120b"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "permissionuuid"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "permissionsId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "PK_d422dabc78ff74a8dab6583da02" PRIMARY KEY ("permissionsId")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "rolesId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "PK_d422dabc78ff74a8dab6583da02"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "PK_7931614007a93423204b4b73240" PRIMARY KEY ("rolesId", "permissionsId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME CONSTRAINT "PK_eb213c3c5ab595f0d0b3b759daf" TO "PK_cd27695a2971731e9fc91b380b3"`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME COLUMN "rolesRoleuuid" TO "rolesId"`);
        await queryRunner.query(`CREATE INDEX "IDX_13380e7efec83468d73fc37938" ON "user_roles" ("rolesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d422dabc78ff74a8dab6583da0" ON "role_permissions" ("permissionsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cb93c5877d37e954e2aa59e52" ON "role_permissions" ("rolesId") `);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_13380e7efec83468d73fc37938e" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_d422dabc78ff74a8dab6583da02" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_0cb93c5877d37e954e2aa59e52c" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
